//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord", IsNullable=false)]
public partial class Verzeichnungseinheit {
    
    private ParentFieldType[] ancestorsField;
    
    private Child[] childrenField;
    
    private string typeNameField;
    
    private string displayNameField;
    
    private string signaturField;
    
    private string alteSignaturField;
    
    private string verwaltungssignaturField;
    
    private string idField;
    
    private string pIDField;
    
    private string titelField;
    
    private DateTimeFieldType entstehungszeitraumField;
    
    private DateTimeFieldType bezugszeitraumField;
    
    private string verzeichnungsstufeField;
    
    private Umfang[] umfangField;
    
    private string verwaltungsgeschichteField;
    
    private string bestandsgeschichteField;
    
    private string abgebendeStelleField;
    
    private string formInhaltField;
    
    private string bewertungKassationField;
    
    private string ordnungKlassifikationField;
    
    private string zugangsbestimmungenField;
    
    private string reproduktionsbestimmungenField;
    
    private Sprache[] spracheField;
    
    private Schrift[] schriftField;
    
    private string physischeBeschaffenheitField;
    
    private string findmittelField;
    
    private object[] standortField;
    
    private string kopienReproduktionenField;
    
    private string verwandtesMaterialField;
    
    private string veroeffentlichungenField;
    
    private string allgemeineAnmerkungenField;
    
    private string verzeichnungsgrundsaetzeField;
    
    private string bemerkungEntstehungszeitraumField;
    
    private Datei[] dateienField;
    
    private string archivalienartenGuidsField;
    
    private Archivalienart[] archivalienartField;
    
    private Provenienz[] provenienzField;
    
    private Akzession[] akzessionField;
    
    private string ueberlieferungsformenGuidsField;
    
    private Ueberlieferungsform[] ueberlieferungsformField;
    
    private string benutzbarkeitField;
    
    private string publikationField;
    
    private string verwertungsrechtField;
    
    private DateTimeFieldType ablaufVerwertungsrechtField;
    
    private System.Nullable<bool> urheberBekanntField;
    
    private DateTimeFieldType todesdatumUrheberField;
    
    private string urheberField;
    
    private string aufbewahrungsortOriginaleField;
    
    private Reproduktionsart[] reproduktionsartField;
    
    private string verzeichnungsstatusField;
    
    private VerzeichnungseinheitErschliessungszustand erschliessungszustandField;
    
    private VerzeichnungseinheitDigitalisierungsgrad digitalisierungsgradField;
    
    private string bearbeiterzeitraumField;
    
    private string interneAnmerkungenField;
    
    private Registerzuweisung[] registerzuordnungField;
    
    private string bemerkungDatierungField;
    
    private string bemerkungProvenienzField;
    
    private VerzeichnungseinheitVerfuegbarkeit verfuegbarkeitField;
    
    private string verfuegbarkeitGuidsField;
    
    private System.Nullable<bool> dateiVorhandenField;
    
    private System.Nullable<bool> digitalVorhandenField;
    
    private string tektonikpfadField;
    
    private VerzeichnungseinheitSchutzfrist schutzfristField;
    
    private Verweis[] verwiesenVonField;
    
    private Verweis[] verwiesenZuField;
    
    private System.Xml.XmlElement customFieldsField;
    
    private DateTimeFieldType schutzfristBasisdatumField;
    
    private DateTimeFieldType schutzfristEnddatumField;
    
    private string linkZuPrimaerdatenField;
    
    private string oBJ_GUIDField;
    
    private string sEQField;
    
    private string iDXField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Parent", IsNullable=false)]
    public ParentFieldType[] Ancestors {
        get {
            return this.ancestorsField;
        }
        set {
            this.ancestorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Child[] Children {
        get {
            return this.childrenField;
        }
        set {
            this.childrenField = value;
        }
    }
    
    /// <remarks/>
    public string TypeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
    
    /// <remarks/>
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public string Signatur {
        get {
            return this.signaturField;
        }
        set {
            this.signaturField = value;
        }
    }
    
    /// <remarks/>
    public string AlteSignatur {
        get {
            return this.alteSignaturField;
        }
        set {
            this.alteSignaturField = value;
        }
    }
    
    /// <remarks/>
    public string Verwaltungssignatur {
        get {
            return this.verwaltungssignaturField;
        }
        set {
            this.verwaltungssignaturField = value;
        }
    }
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string PID {
        get {
            return this.pIDField;
        }
        set {
            this.pIDField = value;
        }
    }
    
    /// <remarks/>
    public string Titel {
        get {
            return this.titelField;
        }
        set {
            this.titelField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType Entstehungszeitraum {
        get {
            return this.entstehungszeitraumField;
        }
        set {
            this.entstehungszeitraumField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType Bezugszeitraum {
        get {
            return this.bezugszeitraumField;
        }
        set {
            this.bezugszeitraumField = value;
        }
    }
    
    /// <remarks/>
    public string Verzeichnungsstufe {
        get {
            return this.verzeichnungsstufeField;
        }
        set {
            this.verzeichnungsstufeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Umfang[] Umfang {
        get {
            return this.umfangField;
        }
        set {
            this.umfangField = value;
        }
    }
    
    /// <remarks/>
    public string Verwaltungsgeschichte {
        get {
            return this.verwaltungsgeschichteField;
        }
        set {
            this.verwaltungsgeschichteField = value;
        }
    }
    
    /// <remarks/>
    public string Bestandsgeschichte {
        get {
            return this.bestandsgeschichteField;
        }
        set {
            this.bestandsgeschichteField = value;
        }
    }
    
    /// <remarks/>
    public string AbgebendeStelle {
        get {
            return this.abgebendeStelleField;
        }
        set {
            this.abgebendeStelleField = value;
        }
    }
    
    /// <remarks/>
    public string FormInhalt {
        get {
            return this.formInhaltField;
        }
        set {
            this.formInhaltField = value;
        }
    }
    
    /// <remarks/>
    public string BewertungKassation {
        get {
            return this.bewertungKassationField;
        }
        set {
            this.bewertungKassationField = value;
        }
    }
    
    /// <remarks/>
    public string OrdnungKlassifikation {
        get {
            return this.ordnungKlassifikationField;
        }
        set {
            this.ordnungKlassifikationField = value;
        }
    }
    
    /// <remarks/>
    public string Zugangsbestimmungen {
        get {
            return this.zugangsbestimmungenField;
        }
        set {
            this.zugangsbestimmungenField = value;
        }
    }
    
    /// <remarks/>
    public string Reproduktionsbestimmungen {
        get {
            return this.reproduktionsbestimmungenField;
        }
        set {
            this.reproduktionsbestimmungenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Sprache[] Sprache {
        get {
            return this.spracheField;
        }
        set {
            this.spracheField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Schrift[] Schrift {
        get {
            return this.schriftField;
        }
        set {
            this.schriftField = value;
        }
    }
    
    /// <remarks/>
    public string PhysischeBeschaffenheit {
        get {
            return this.physischeBeschaffenheitField;
        }
        set {
            this.physischeBeschaffenheitField = value;
        }
    }
    
    /// <remarks/>
    public string Findmittel {
        get {
            return this.findmittelField;
        }
        set {
            this.findmittelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(Gebaeude), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute(typeof(MagazinObjekt), IsNullable=false)]
    public object[] Standort {
        get {
            return this.standortField;
        }
        set {
            this.standortField = value;
        }
    }
    
    /// <remarks/>
    public string KopienReproduktionen {
        get {
            return this.kopienReproduktionenField;
        }
        set {
            this.kopienReproduktionenField = value;
        }
    }
    
    /// <remarks/>
    public string VerwandtesMaterial {
        get {
            return this.verwandtesMaterialField;
        }
        set {
            this.verwandtesMaterialField = value;
        }
    }
    
    /// <remarks/>
    public string Veroeffentlichungen {
        get {
            return this.veroeffentlichungenField;
        }
        set {
            this.veroeffentlichungenField = value;
        }
    }
    
    /// <remarks/>
    public string AllgemeineAnmerkungen {
        get {
            return this.allgemeineAnmerkungenField;
        }
        set {
            this.allgemeineAnmerkungenField = value;
        }
    }
    
    /// <remarks/>
    public string Verzeichnungsgrundsaetze {
        get {
            return this.verzeichnungsgrundsaetzeField;
        }
        set {
            this.verzeichnungsgrundsaetzeField = value;
        }
    }
    
    /// <remarks/>
    public string BemerkungEntstehungszeitraum {
        get {
            return this.bemerkungEntstehungszeitraumField;
        }
        set {
            this.bemerkungEntstehungszeitraumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Datei[] Dateien {
        get {
            return this.dateienField;
        }
        set {
            this.dateienField = value;
        }
    }
    
    /// <remarks/>
    public string ArchivalienartenGuids {
        get {
            return this.archivalienartenGuidsField;
        }
        set {
            this.archivalienartenGuidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Archivalienart[] Archivalienart {
        get {
            return this.archivalienartField;
        }
        set {
            this.archivalienartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Provenienz[] Provenienz {
        get {
            return this.provenienzField;
        }
        set {
            this.provenienzField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Akzession[] Akzession {
        get {
            return this.akzessionField;
        }
        set {
            this.akzessionField = value;
        }
    }
    
    /// <remarks/>
    public string UeberlieferungsformenGuids {
        get {
            return this.ueberlieferungsformenGuidsField;
        }
        set {
            this.ueberlieferungsformenGuidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Ueberlieferungsform[] Ueberlieferungsform {
        get {
            return this.ueberlieferungsformField;
        }
        set {
            this.ueberlieferungsformField = value;
        }
    }
    
    /// <remarks/>
    public string Benutzbarkeit {
        get {
            return this.benutzbarkeitField;
        }
        set {
            this.benutzbarkeitField = value;
        }
    }
    
    /// <remarks/>
    public string Publikation {
        get {
            return this.publikationField;
        }
        set {
            this.publikationField = value;
        }
    }
    
    /// <remarks/>
    public string Verwertungsrecht {
        get {
            return this.verwertungsrechtField;
        }
        set {
            this.verwertungsrechtField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType AblaufVerwertungsrecht {
        get {
            return this.ablaufVerwertungsrechtField;
        }
        set {
            this.ablaufVerwertungsrechtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> UrheberBekannt {
        get {
            return this.urheberBekanntField;
        }
        set {
            this.urheberBekanntField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType TodesdatumUrheber {
        get {
            return this.todesdatumUrheberField;
        }
        set {
            this.todesdatumUrheberField = value;
        }
    }
    
    /// <remarks/>
    public string Urheber {
        get {
            return this.urheberField;
        }
        set {
            this.urheberField = value;
        }
    }
    
    /// <remarks/>
    public string AufbewahrungsortOriginale {
        get {
            return this.aufbewahrungsortOriginaleField;
        }
        set {
            this.aufbewahrungsortOriginaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Reproduktionsart[] Reproduktionsart {
        get {
            return this.reproduktionsartField;
        }
        set {
            this.reproduktionsartField = value;
        }
    }
    
    /// <remarks/>
    public string Verzeichnungsstatus {
        get {
            return this.verzeichnungsstatusField;
        }
        set {
            this.verzeichnungsstatusField = value;
        }
    }
    
    /// <remarks/>
    public VerzeichnungseinheitErschliessungszustand Erschliessungszustand {
        get {
            return this.erschliessungszustandField;
        }
        set {
            this.erschliessungszustandField = value;
        }
    }
    
    /// <remarks/>
    public VerzeichnungseinheitDigitalisierungsgrad Digitalisierungsgrad {
        get {
            return this.digitalisierungsgradField;
        }
        set {
            this.digitalisierungsgradField = value;
        }
    }
    
    /// <remarks/>
    public string Bearbeiterzeitraum {
        get {
            return this.bearbeiterzeitraumField;
        }
        set {
            this.bearbeiterzeitraumField = value;
        }
    }
    
    /// <remarks/>
    public string InterneAnmerkungen {
        get {
            return this.interneAnmerkungenField;
        }
        set {
            this.interneAnmerkungenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Registerzuweisung[] Registerzuordnung {
        get {
            return this.registerzuordnungField;
        }
        set {
            this.registerzuordnungField = value;
        }
    }
    
    /// <remarks/>
    public string BemerkungDatierung {
        get {
            return this.bemerkungDatierungField;
        }
        set {
            this.bemerkungDatierungField = value;
        }
    }
    
    /// <remarks/>
    public string BemerkungProvenienz {
        get {
            return this.bemerkungProvenienzField;
        }
        set {
            this.bemerkungProvenienzField = value;
        }
    }
    
    /// <remarks/>
    public VerzeichnungseinheitVerfuegbarkeit Verfuegbarkeit {
        get {
            return this.verfuegbarkeitField;
        }
        set {
            this.verfuegbarkeitField = value;
        }
    }
    
    /// <remarks/>
    public string VerfuegbarkeitGuids {
        get {
            return this.verfuegbarkeitGuidsField;
        }
        set {
            this.verfuegbarkeitGuidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> DateiVorhanden {
        get {
            return this.dateiVorhandenField;
        }
        set {
            this.dateiVorhandenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> DigitalVorhanden {
        get {
            return this.digitalVorhandenField;
        }
        set {
            this.digitalVorhandenField = value;
        }
    }
    
    /// <remarks/>
    public string Tektonikpfad {
        get {
            return this.tektonikpfadField;
        }
        set {
            this.tektonikpfadField = value;
        }
    }
    
    /// <remarks/>
    public VerzeichnungseinheitSchutzfrist Schutzfrist {
        get {
            return this.schutzfristField;
        }
        set {
            this.schutzfristField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Verweis[] VerwiesenVon {
        get {
            return this.verwiesenVonField;
        }
        set {
            this.verwiesenVonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Verweis[] VerwiesenZu {
        get {
            return this.verwiesenZuField;
        }
        set {
            this.verwiesenZuField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement CustomFields {
        get {
            return this.customFieldsField;
        }
        set {
            this.customFieldsField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType SchutzfristBasisdatum {
        get {
            return this.schutzfristBasisdatumField;
        }
        set {
            this.schutzfristBasisdatumField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType SchutzfristEnddatum {
        get {
            return this.schutzfristEnddatumField;
        }
        set {
            this.schutzfristEnddatumField = value;
        }
    }
    
    /// <remarks/>
    public string LinkZuPrimaerdaten {
        get {
            return this.linkZuPrimaerdatenField;
        }
        set {
            this.linkZuPrimaerdatenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SEQ {
        get {
            return this.sEQField;
        }
        set {
            this.sEQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IDX {
        get {
            return this.iDXField;
        }
        set {
            this.iDXField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class ParentFieldType {
    
    private string oBJ_GUIDField;
    
    private decimal typeIdField;
    
    private string typeKeyField;
    
    private decimal depthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal TypeId {
        get {
            return this.typeIdField;
        }
        set {
            this.typeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeKey {
        get {
            return this.typeKeyField;
        }
        set {
            this.typeKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Verweis {
    
    private string bemerkungField;
    
    private VerweisVE1 vE1Field;
    
    private VerweisVE2 vE2Field;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bemerkung {
        get {
            return this.bemerkungField;
        }
        set {
            this.bemerkungField = value;
        }
    }
    
    /// <remarks/>
    public VerweisVE1 VE1 {
        get {
            return this.vE1Field;
        }
        set {
            this.vE1Field = value;
        }
    }
    
    /// <remarks/>
    public VerweisVE2 VE2 {
        get {
            return this.vE2Field;
        }
        set {
            this.vE2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class VerweisVE1 {
    
    private Child itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Child")]
    public Child Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Child {
    
    private string typeNameField;
    
    private string displayNameField;
    
    private string sortierungField;
    
    private string signaturField;
    
    private string kuerzelField;
    
    private string titelField;
    
    private DateTimeFieldType entstehungszeitraumField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string TypeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
    
    /// <remarks/>
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public string Sortierung {
        get {
            return this.sortierungField;
        }
        set {
            this.sortierungField = value;
        }
    }
    
    /// <remarks/>
    public string Signatur {
        get {
            return this.signaturField;
        }
        set {
            this.signaturField = value;
        }
    }
    
    /// <remarks/>
    public string Kuerzel {
        get {
            return this.kuerzelField;
        }
        set {
            this.kuerzelField = value;
        }
    }
    
    /// <remarks/>
    public string Titel {
        get {
            return this.titelField;
        }
        set {
            this.titelField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType Entstehungszeitraum {
        get {
            return this.entstehungszeitraumField;
        }
        set {
            this.entstehungszeitraumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class DateTimeFieldType {
    
    private System.Nullable<System.DateTime> startField;
    
    private System.Nullable<System.DateTime> endField;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> End {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class VerweisVE2 {
    
    private Child itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Child")]
    public Child Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Schutzfrist {
    
    private System.Nullable<decimal> fristField;
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Frist {
        get {
            return this.fristField;
        }
        set {
            this.fristField = value;
        }
    }
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Verfuegbarkeit {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Registertyp {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Register {
    
    private string bezeichnungField;
    
    private string bemerkungField;
    
    private RegisterRegistertyp registertypField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    public string Bemerkung {
        get {
            return this.bemerkungField;
        }
        set {
            this.bemerkungField = value;
        }
    }
    
    /// <remarks/>
    public RegisterRegistertyp Registertyp {
        get {
            return this.registertypField;
        }
        set {
            this.registertypField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class RegisterRegistertyp {
    
    private Registertyp itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Registertyp")]
    public Registertyp Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Registerzuweisung {
    
    private RegisterzuweisungRegistereintrag registereintragField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public RegisterzuweisungRegistereintrag Registereintrag {
        get {
            return this.registereintragField;
        }
        set {
            this.registereintragField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class RegisterzuweisungRegistereintrag {
    
    private Register itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Register")]
    public Register Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Digitalisierungsgrad {
    
    private string digitalisierungsgrad1Field;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Digitalisierungsgrad")]
    public string Digitalisierungsgrad1 {
        get {
            return this.digitalisierungsgrad1Field;
        }
        set {
            this.digitalisierungsgrad1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Erschliessungszustand {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Reproduktionsart {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Ueberlieferungsform {
    
    private string bezeichnungField;
    
    private string formField;
    
    private System.Nullable<decimal> sortierungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    public string Form {
        get {
            return this.formField;
        }
        set {
            this.formField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Sortierung {
        get {
            return this.sortierungField;
        }
        set {
            this.sortierungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Akzession {
    
    private string akzessionsnummerField;
    
    private string titelField;
    
    private DateTimeFieldType datumField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Akzessionsnummer {
        get {
            return this.akzessionsnummerField;
        }
        set {
            this.akzessionsnummerField = value;
        }
    }
    
    /// <remarks/>
    public string Titel {
        get {
            return this.titelField;
        }
        set {
            this.titelField = value;
        }
    }
    
    /// <remarks/>
    public DateTimeFieldType Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Provenienz {
    
    private string offiziellerNameField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string OffiziellerName {
        get {
            return this.offiziellerNameField;
        }
        set {
            this.offiziellerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Archivalienart {
    
    private string bezeichnungField;
    
    private System.Nullable<decimal> sortierungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Sortierung {
        get {
            return this.sortierungField;
        }
        set {
            this.sortierungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class ArtDatei {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class RenditionType {
    
    private string extensionField;
    
    private string ansichtField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ansicht {
        get {
            return this.ansichtField;
        }
        set {
            this.ansichtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class VersionType {
    
    private RenditionType[] itemsField;
    
    private decimal nrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rendition")]
    public RenditionType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Nr {
        get {
            return this.nrField;
        }
        set {
            this.nrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class DocumentFieldType {
    
    private VersionType[] itemsField;
    
    private string idField;
    
    private string fileNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Version")]
    public VersionType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Datei {
    
    private string titelField;
    
    private DocumentFieldType fileField;
    
    private string fileExtensionField;
    
    private string fileSizeField;
    
    private string fileTypeField;
    
    private System.Nullable<decimal> fileTypeOrderField;
    
    private string bemerkungenField;
    
    private DateiArt artField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Titel {
        get {
            return this.titelField;
        }
        set {
            this.titelField = value;
        }
    }
    
    /// <remarks/>
    public DocumentFieldType File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    public string FileExtension {
        get {
            return this.fileExtensionField;
        }
        set {
            this.fileExtensionField = value;
        }
    }
    
    /// <remarks/>
    public string FileSize {
        get {
            return this.fileSizeField;
        }
        set {
            this.fileSizeField = value;
        }
    }
    
    /// <remarks/>
    public string FileType {
        get {
            return this.fileTypeField;
        }
        set {
            this.fileTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> FileTypeOrder {
        get {
            return this.fileTypeOrderField;
        }
        set {
            this.fileTypeOrderField = value;
        }
    }
    
    /// <remarks/>
    public string Bemerkungen {
        get {
            return this.bemerkungenField;
        }
        set {
            this.bemerkungenField = value;
        }
    }
    
    /// <remarks/>
    public DateiArt Art {
        get {
            return this.artField;
        }
        set {
            this.artField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class DateiArt {
    
    private ArtDatei itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArtDatei")]
    public ArtDatei Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class ParentM {
    
    private string kuerzelField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Kuerzel {
        get {
            return this.kuerzelField;
        }
        set {
            this.kuerzelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class ParentG {
    
    private string kuerzelField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Kuerzel {
        get {
            return this.kuerzelField;
        }
        set {
            this.kuerzelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class ArtMagazinObjekt {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class MagazinObjekt {
    
    private string kuerzelField;
    
    private string bezeichnungField;
    
    private MagazinObjektArt artField;
    
    private MagazinObjektParentGebauede parentGebauedeField;
    
    private MagazinObjektParentMagazinobjekt parentMagazinobjektField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Kuerzel {
        get {
            return this.kuerzelField;
        }
        set {
            this.kuerzelField = value;
        }
    }
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    public MagazinObjektArt Art {
        get {
            return this.artField;
        }
        set {
            this.artField = value;
        }
    }
    
    /// <remarks/>
    public MagazinObjektParentGebauede ParentGebauede {
        get {
            return this.parentGebauedeField;
        }
        set {
            this.parentGebauedeField = value;
        }
    }
    
    /// <remarks/>
    public MagazinObjektParentMagazinobjekt ParentMagazinobjekt {
        get {
            return this.parentMagazinobjektField;
        }
        set {
            this.parentMagazinobjektField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class MagazinObjektArt {
    
    private ArtMagazinObjekt itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArtMagazinObjekt")]
    public ArtMagazinObjekt Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class MagazinObjektParentGebauede {
    
    private ParentG itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Gebaeude")]
    public ParentG Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class MagazinObjektParentMagazinobjekt {
    
    private ParentM itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MagazinObjekt")]
    public ParentM Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Gebaeude {
    
    private string kuerzelField;
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Kuerzel {
        get {
            return this.kuerzelField;
        }
        set {
            this.kuerzelField = value;
        }
    }
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Schrift {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Sprache {
    
    private string bezeichnungField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class Umfang {
    
    private string masseinheitField;
    
    private System.Nullable<decimal> wertField;
    
    private string oBJ_GUIDField;
    
    /// <remarks/>
    public string Masseinheit {
        get {
            return this.masseinheitField;
        }
        set {
            this.masseinheitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Wert {
        get {
            return this.wertField;
        }
        set {
            this.wertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OBJ_GUID {
        get {
            return this.oBJ_GUIDField;
        }
        set {
            this.oBJ_GUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class VerzeichnungseinheitErschliessungszustand {
    
    private Erschliessungszustand itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Erschliessungszustand")]
    public Erschliessungszustand Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class VerzeichnungseinheitDigitalisierungsgrad {
    
    private Digitalisierungsgrad itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Digitalisierungsgrad")]
    public Digitalisierungsgrad Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class VerzeichnungseinheitVerfuegbarkeit {
    
    private Verfuegbarkeit itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Verfuegbarkeit")]
    public Verfuegbarkeit Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cmiag.ch/cdws/CMIArchiveRecord")]
public partial class VerzeichnungseinheitSchutzfrist {
    
    private Schutzfrist itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Schutzfrist")]
    public Schutzfrist Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}
