//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// CM Informatik AG
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace CMI.Contract.Common.Entities
{

    public static partial class CollectionConverter
    {

        public static CollectionDto ToDto(this CMI.Access.Sql.Viaduc.EF.Collection source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static CollectionDto ToDtoWithRelated(this CMI.Access.Sql.Viaduc.EF.Collection source, int level)
        {
            if (source == null)
              return null;

            var target = new CollectionDto();

            // Properties
            target.CollectionId = source.CollectionId;
            target.ParentId = source.ParentId;
            target.Language = source.Language;
            target.Title = source.Title;
            target.DescriptionShort = source.DescriptionShort;
            target.Description = source.Description;
            target.ValidFrom = source.ValidFrom;
            target.ValidTo = source.ValidTo;
            target.CollectionTypeId = source.CollectionTypeId;
            target.Image = source.Image;
            target.Thumbnail = source.Thumbnail;
            target.ImageAltText = source.ImageAltText;
            target.ImageMimeType = source.ImageMimeType;
            target.Link = source.Link;
            target.CollectionPath = source.CollectionPath;
            target.SortOrder = source.SortOrder;
            target.CreatedOn = source.CreatedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedOn = source.ModifiedOn;
            target.ModifiedBy = source.ModifiedBy;

            // Navigation Properties
            if (level > 0) {
              target.ChildCollections = source.ChildCollections.ToDtosWithRelated(level - 1);
              target.Parent = source.Parent.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static CMI.Access.Sql.Viaduc.EF.Collection ToEntity(this CollectionDto source)
        {
            if (source == null)
              return null;

            var target = new CMI.Access.Sql.Viaduc.EF.Collection();

            // Properties
            target.CollectionId = source.CollectionId;
            target.ParentId = source.ParentId;
            target.Language = source.Language;
            target.Title = source.Title;
            target.DescriptionShort = source.DescriptionShort;
            target.Description = source.Description;
            target.ValidFrom = source.ValidFrom;
            target.ValidTo = source.ValidTo;
            target.CollectionTypeId = source.CollectionTypeId;
            target.Image = source.Image;
            target.Thumbnail = source.Thumbnail;
            target.ImageAltText = source.ImageAltText;
            target.ImageMimeType = source.ImageMimeType;
            target.Link = source.Link;
            target.CollectionPath = source.CollectionPath;
            target.SortOrder = source.SortOrder;
            target.CreatedOn = source.CreatedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedOn = source.ModifiedOn;
            target.ModifiedBy = source.ModifiedBy;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<CollectionDto> ToDtos(this IEnumerable<CMI.Access.Sql.Viaduc.EF.Collection> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<CollectionDto> ToDtosWithRelated(this IEnumerable<CMI.Access.Sql.Viaduc.EF.Collection> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<CMI.Access.Sql.Viaduc.EF.Collection> ToEntities(this IEnumerable<CollectionDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(CMI.Access.Sql.Viaduc.EF.Collection source, CollectionDto target);

        static partial void OnEntityCreating(CollectionDto source, CMI.Access.Sql.Viaduc.EF.Collection target);

    }

    public static partial class CollectionListItemConverter
    {

        public static CollectionListItemDto ToDto(this CMI.Access.Sql.Viaduc.EF.CollectionListItem source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static CollectionListItemDto ToDtoWithRelated(this CMI.Access.Sql.Viaduc.EF.CollectionListItem source, int level)
        {
            if (source == null)
              return null;

            var target = new CollectionListItemDto();

            // Properties
            target.CollectionId = source.CollectionId;
            target.ParentId = source.ParentId;
            target.Language = source.Language;
            target.Title = source.Title;
            target.DescriptionShort = source.DescriptionShort;
            target.Description = source.Description;
            target.ValidFrom = source.ValidFrom;
            target.ValidTo = source.ValidTo;
            target.CollectionTypeId = source.CollectionTypeId;
            target.ImageAltText = source.ImageAltText;
            target.ImageMimeType = source.ImageMimeType;
            target.Link = source.Link;
            target.CollectionPath = source.CollectionPath;
            target.SortOrder = source.SortOrder;
            target.CreatedOn = source.CreatedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedOn = source.ModifiedOn;
            target.ModifiedBy = source.ModifiedBy;
            target.Parent = source.Parent;
            target.ChildCollections = source.ChildCollections;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static CMI.Access.Sql.Viaduc.EF.CollectionListItem ToEntity(this CollectionListItemDto source)
        {
            if (source == null)
              return null;

            var target = new CMI.Access.Sql.Viaduc.EF.CollectionListItem();

            // Properties
            target.CollectionId = source.CollectionId;
            target.ParentId = source.ParentId;
            target.Language = source.Language;
            target.Title = source.Title;
            target.DescriptionShort = source.DescriptionShort;
            target.Description = source.Description;
            target.ValidFrom = source.ValidFrom;
            target.ValidTo = source.ValidTo;
            target.CollectionTypeId = source.CollectionTypeId;
            target.ImageAltText = source.ImageAltText;
            target.ImageMimeType = source.ImageMimeType;
            target.Link = source.Link;
            target.CollectionPath = source.CollectionPath;
            target.SortOrder = source.SortOrder;
            target.CreatedOn = source.CreatedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedOn = source.ModifiedOn;
            target.ModifiedBy = source.ModifiedBy;
            target.Parent = source.Parent;
            target.ChildCollections = source.ChildCollections;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<CollectionListItemDto> ToDtos(this IEnumerable<CMI.Access.Sql.Viaduc.EF.CollectionListItem> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<CollectionListItemDto> ToDtosWithRelated(this IEnumerable<CMI.Access.Sql.Viaduc.EF.CollectionListItem> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<CMI.Access.Sql.Viaduc.EF.CollectionListItem> ToEntities(this IEnumerable<CollectionListItemDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(CMI.Access.Sql.Viaduc.EF.CollectionListItem source, CollectionListItemDto target);

        static partial void OnEntityCreating(CollectionListItemDto source, CMI.Access.Sql.Viaduc.EF.CollectionListItem target);

    }

    public static partial class ApplicationUserConverter
    {

        public static ApplicationUserDto ToDto(this CMI.Access.Sql.Viaduc.EF.ApplicationUser source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ApplicationUserDto ToDtoWithRelated(this CMI.Access.Sql.Viaduc.EF.ApplicationUser source, int level)
        {
            if (source == null)
              return null;

            var target = new ApplicationUserDto();

            // Properties
            target.ID = source.ID;
            target.FamilyName = source.FamilyName;
            target.FirstName = source.FirstName;
            target.Organization = source.Organization;
            target.Street = source.Street;
            target.StreetAttachment = source.StreetAttachment;
            target.ZipCode = source.ZipCode;
            target.Town = source.Town;
            target.CountryCode = source.CountryCode;
            target.EmailAddress = source.EmailAddress;
            target.PhoneNumber = source.PhoneNumber;
            target.SkypeName = source.SkypeName;
            target.Setting = source.Setting;
            target.Claims = source.Claims;
            target.Created = source.Created;
            target.Updated = source.Updated;
            target.Fulltext = source.Fulltext;
            target.UserExtId = source.UserExtId;
            target.Language = source.Language;
            target.CreatedOn = source.CreatedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedOn = source.ModifiedOn;
            target.ModifiedBy = source.ModifiedBy;
            target.Birthday = source.Birthday;
            target.FabasoftDossier = source.FabasoftDossier;
            target.ReasonForRejection = source.ReasonForRejection;
            target.IsInternalUser = source.IsInternalUser;
            target.RolePublicClient = source.RolePublicClient;
            target.EiamRoles = source.EiamRoles;
            target.ResearcherGroup = source.ResearcherGroup;
            target.BarInternalConsultation = source.BarInternalConsultation;
            target.IdentifierDocument = source.IdentifierDocument;
            target.MobileNumber = source.MobileNumber;
            target.ReasonForRejectionDate = source.ReasonForRejectionDate;
            target.DownloadLimitDisabledUntil = source.DownloadLimitDisabledUntil;
            target.DigitalisierungsbeschraenkungAufgehobenBis = source.DigitalisierungsbeschraenkungAufgehobenBis;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static CMI.Access.Sql.Viaduc.EF.ApplicationUser ToEntity(this ApplicationUserDto source)
        {
            if (source == null)
              return null;

            var target = new CMI.Access.Sql.Viaduc.EF.ApplicationUser();

            // Properties
            target.ID = source.ID;
            target.FamilyName = source.FamilyName;
            target.FirstName = source.FirstName;
            target.Organization = source.Organization;
            target.Street = source.Street;
            target.StreetAttachment = source.StreetAttachment;
            target.ZipCode = source.ZipCode;
            target.Town = source.Town;
            target.CountryCode = source.CountryCode;
            target.EmailAddress = source.EmailAddress;
            target.PhoneNumber = source.PhoneNumber;
            target.SkypeName = source.SkypeName;
            target.Setting = source.Setting;
            target.Claims = source.Claims;
            target.Created = source.Created;
            target.Updated = source.Updated;
            target.Fulltext = source.Fulltext;
            target.UserExtId = source.UserExtId;
            target.Language = source.Language;
            target.CreatedOn = source.CreatedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedOn = source.ModifiedOn;
            target.ModifiedBy = source.ModifiedBy;
            target.Birthday = source.Birthday;
            target.FabasoftDossier = source.FabasoftDossier;
            target.ReasonForRejection = source.ReasonForRejection;
            target.IsInternalUser = source.IsInternalUser;
            target.RolePublicClient = source.RolePublicClient;
            target.EiamRoles = source.EiamRoles;
            target.ResearcherGroup = source.ResearcherGroup;
            target.BarInternalConsultation = source.BarInternalConsultation;
            target.IdentifierDocument = source.IdentifierDocument;
            target.MobileNumber = source.MobileNumber;
            target.ReasonForRejectionDate = source.ReasonForRejectionDate;
            target.DownloadLimitDisabledUntil = source.DownloadLimitDisabledUntil;
            target.DigitalisierungsbeschraenkungAufgehobenBis = source.DigitalisierungsbeschraenkungAufgehobenBis;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ApplicationUserDto> ToDtos(this IEnumerable<CMI.Access.Sql.Viaduc.EF.ApplicationUser> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ApplicationUserDto> ToDtosWithRelated(this IEnumerable<CMI.Access.Sql.Viaduc.EF.ApplicationUser> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<CMI.Access.Sql.Viaduc.EF.ApplicationUser> ToEntities(this IEnumerable<ApplicationUserDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(CMI.Access.Sql.Viaduc.EF.ApplicationUser source, ApplicationUserDto target);

        static partial void OnEntityCreating(ApplicationUserDto source, CMI.Access.Sql.Viaduc.EF.ApplicationUser target);

    }

}
