//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Manager.Harvest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class DbConnectionSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static DbConnectionSetting defaultInstance = ((DbConnectionSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DbConnectionSetting())));
        
        public static DbConnectionSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/CMI.Access.Sql.Lesesaal.EF.Lesesaal.csdl|res://*/CMI.Access.Sql.Lesesaal.EF.Lesesaal.ssdl|res://*/CMI.Access.Sql.Lesesaal.EF.Lesesaal.msl;provider=System.Data.SqlClient;provider connection string=""@@CMI.SqlServer.DbConnectionSetting.ConnectionStringEF@@""")]
        public string ConnectionStringEF {
            get {
                return ((string)(this["ConnectionStringEF"]));
            }
        }
    }
}
