//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Manager.Asset.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class ViewerFileLocation : global::System.Configuration.ApplicationSettingsBase {
        
        private static ViewerFileLocation defaultInstance = ((ViewerFileLocation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ViewerFileLocation())));
        
        public static ViewerFileLocation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\ManifestTest\\manifests")]
        public string ManifestOutputSaveDirectory {
            get {
                return ((string)(this["ManifestOutputSaveDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\ManifestTest\\content")]
        public string ContentOutputSaveDirectory {
            get {
                return ((string)(this["ContentOutputSaveDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\ManifestTest\\ocr")]
        public string OcrOutputSaveDirectory {
            get {
                return ((string)(this["OcrOutputSaveDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\ManifestTest\\images")]
        public string ImageOutputSaveDirectory {
            get {
                return ((string)(this["ImageOutputSaveDirectory"]));
            }
        }
    }
}
