name: CMI Lesesaal Release Build (Full)

on:
  workflow_dispatch:
    inputs:
        comment:
          description: 'Bemerkung'
          required: false
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Zip artifacts
        if: ${{ needs.build-services.outputs.tagExists == false }}
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ github.workspace }}/CMI/CustomerScripts/ETH/* -DestinationPath ${{ github.workspace }}\test.zip

      - name: Create Lesesaal Release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test
          release_name: test
          draft: false

      - name: Upload Release Asset 2
        uses: actions/upload-release-asset@v1
        if: ${{ needs.build-services.outputs.tagExists == false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/test.zip
          asset_name: test.zip
          asset_content_type: application/zip
