name: CMI Lesesaal CI Build (Full)

on:
  workflow_dispatch:
    inputs:
        comment:
          description: 'Bemerkung'
          required: false
  pull_request:
    branches: [ develop ]

jobs:
  build-frontend-client:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./CMI/Web.Clients/web-frontend
      WORKING_DIR_CORE: ./CMI/Web.Clients/web-core
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build and install web-core
      working-directory: ${{ env.WORKING_DIR_CORE }}
      run: |
        npm i
        npm run build
      
    - name: Install Dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        cp ${{ env.WORKING_DIR_CORE}}/dist/@cmi/viaduc-web-core ${{ env.WORKING_DIR_CORE}}/node_modules/@cmi/viaduc-web-core

        ls ${{ env.WORKING_DIR_CORE}}/node_modules/@cmi/viaduc-web-core
        npm run link
        npm i

    - name: Test
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run test-github
      
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run build-prod

  build-management-client:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./CMI/Web.Clients/web-management
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install Dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        npm run link
        npm i
      env:
        NPM_AUTH_TOKEN: ${{ secrets.MYGET_PUSH_APIKEY }}

    - name: Test
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run test-github
      
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run build-prod

  build-services:
    runs-on: windows-latest
    env:
      SOLUTION: cmi-lesesaal.sln
      ON_BUILDSERVER: 'True'
    outputs:
      version: ${{ env.GitBuildVersion }}
      tagExists: ${{ steps.checkTag.outputs.exist }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore Nugets
        run: nuget restore ${{ env.SOLUTION }}
        
      - name: Build Services
        run: msbuild ${{ env.SOLUTION }} /t:Rebuild /p:Configuration=Debug 
        
      - name: Test and Cover
        shell: pwsh
        run: |
          Invoke-WebRequest "https://download.jetbrains.com/resharper/dotUltimate.2021.2.1/JetBrains.dotCover.CommandLineTools.2021.2.1.zip" -OutFile "dotcover.zip"
          Expand-Archive -Path dotcover.zip -DestinationPath .\dotcover
          $assemblies = (ls -r Test\*\**\bin\debug\*.Tests.dll | where-object { $_.FullName -notlike "*.Performance.Tests.dll" } | % { $_.FullName } | sort-object -Unique)
          .\dotcover\dotCover.exe cover /TargetExecutable="packages\NUnit.ConsoleRunner.3.14.0\tools\nunit3-console.exe" /TargetArguments="$assemblies" /Filters=+:CMI.* /Output="./coverage/services_coverage.html" /ReportType="HTML"