name: CMI Lesesaal CI Build (Full)

on:
  workflow_dispatch:
    inputs:
        comment:
          description: 'Bemerkung'
          required: false
  pull_request:
    branches: [ develop ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./CMI/Web.Clients/web-core
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      working-directory: ${{ env.WORKING_DIR }}
        run: npm i --legacy-peer-deps
    
    - name: Replace licenses
      working-directory: ${{ env.WORKING_DIR }}/src/lib/wijmo 
      run: |
        sed -i "s/secrets.WIJMO_LICENSEKEY/${{ secrets.WIJMO_LICENSEKEY }}/" wijmo.licensekey.ts

    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        npm run build

    - name: Save Dist
      uses: actions/upload-artifact@v4
      with:
        name: web-core
        path: ${{ env.WORKING_DIR }}/dist/@cmi/lesesaal-web-core/**
        retention-days: 1
      
  build-frontend-client:
    needs: build-core
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./CMI/Web.Clients/web-frontend
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      
    - name: Install Dependencies
      working-directory: ${{ env.WORKING_DIR }}
        run: npm i --legacy-peer-deps

    - name: Restore Core from artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ env.WORKING_DIR}}/node_modules/@cmi/lesesaal-web-core
        name: web-core

    - name: Test
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run test-github
      
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run build-prod

  build-management-client:
    needs: build-core
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./CMI/Web.Clients/web-management
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install Dependencies
      working-directory: ${{ env.WORKING_DIR }}
        run: npm i --legacy-peer-deps
      env:
        NPM_AUTH_TOKEN: ${{ secrets.MYGET_PUSH_APIKEY }}

    - name: Restore Core from artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ env.WORKING_DIR}}/node_modules/@cmi/lesesaal-web-core
        name: web-core

    - name: Test
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run test-github
      
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run build-prod

  build-services:
    runs-on: windows-latest
    env:
      SOLUTION: cmi-lesesaal.sln
      ON_BUILDSERVER: 'True'
    outputs:
      version: ${{ env.GitBuildVersion }}
      tagExists: ${{ steps.checkTag.outputs.exist }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore Nugets
        run: nuget restore ${{ env.SOLUTION }}
        
      - name: Build Services
        run: msbuild ${{ env.SOLUTION }} /t:Rebuild /p:Configuration=Release 
        
      - name: Test and Cover
        shell: pwsh
        run: |
          Invoke-WebRequest "https://download.jetbrains.com/resharper/dotUltimate.2021.2.1/JetBrains.dotCover.CommandLineTools.2021.2.1.zip" -OutFile "dotcover.zip"
          Expand-Archive -Path dotcover.zip -DestinationPath .\dotcover
          $assemblies = (ls -r Test\*\**\bin\debug\*.Tests.dll | where-object { $_.FullName -notlike "*.Performance.Tests.dll" } | % { $_.FullName } | sort-object -Unique)
          .\dotcover\dotCover.exe cover /TargetExecutable="packages\NUnit.ConsoleRunner.3.16.0\tools\nunit3-console.exe" /TargetArguments="$assemblies" /Filters=+:CMI.* /Output="./coverage/services_coverage.html" /ReportType="HTML"
