name: CMI Lesesaal Release Build (Full)

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Gewünschter Branch (in allen Repositories)'
        required: true
        default: 'develop'

jobs:
  build-frontend-client:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./CMI/Web.Clients/web-frontend
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://myget.org/F/cmiag-nuget/npm/
        always-auth: true
        
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install Dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        npm i
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MYGET_PUSH_APIKEY }}

    - name: Test
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run test-github
      
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run build-prod
      
    - name: Save Dist
      uses: actions/upload-artifact@v2
      with:
        name: frontend-client
        path: ./dist/**
        retention-days: 1