name: CMI Lesesaal Release Build (Full)

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Gewünschter Branch (in allen Repositories)'
        required: true
        default: 'develop'

jobs:
  build-services:
    runs-on: windows-latest
    env:
      SOLUTION: cmi-lesesaal.sln
    outputs:
      version: ${{ env.GitBuildVersion }}
      tagExists: ${{ steps.checkTag.outputs.exist }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore Nugets
        working-directory: ./vservices
        run: nuget restore ${{ env.SOLUTION }}
        
      - name: Build Services
        run: msbuild ${{ env.SOLUTION }} /t:Rebuild /p:Configuration=Release 
        
      - name: Publish Frontend API
        run: msbuild "${{ github.workspace }}\CMI\Web\CMI.Web.Frontend\CMI.Web.Frontend.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:WebPublish /p:WebPublishMethod=FileSystem /p:ExcludeApp_Data=True /p:DeleteExistingFiles=True /p:publishUrl="${{ github.workspace }}\frontendartefacts"
            
      - name: Publish Management API
        run: msbuild "${{ github.workspace }}\CMI\Web\CMI.Web.Management\CMI.Web.Management.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:WebPublish /p:WebPublishMethod=FileSystem /p:ExcludeApp_Data=True /p:DeleteExistingFiles=True /p:publishUrl="${{ github.workspace }}\managementartefacts"
                     
      - name: Test and Cover
        shell: pwsh
        run: |
          Invoke-WebRequest "https://download.jetbrains.com/resharper/dotUltimate.2021.2.1/JetBrains.dotCover.CommandLineTools.2021.2.1.zip" -OutFile "dotcover.zip"
          Expand-Archive -Path dotcover.zip -DestinationPath .\dotcover
          $assemblies = (ls -r Test\*\**\bin\release\*.Tests.dll | where-object { $_.FullName -notlike "*.Performance.Tests.dll" } | % { $_.FullName } | sort-object -Unique)
          .\dotcover\dotCover.exe cover /TargetExecutable="packages\NUnit.ConsoleRunner.3.14.0\tools\nunit3-console.exe" /TargetArguments="$assemblies" /Filters=+:CMI.* /Output="./coverage/services_coverage.html" /ReportType="HTML"
      
      - name: Save Coverage
        uses: actions/upload-artifact@v2
        with:
          name: lesesaal-services-coverage
          path: ./coverage/**
          retention-days: 10
        
     