name: .NET Framework (CI)

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest
    env: 
      ON_BUILDSERVER: 'True'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore Nugets
        run: nuget restore cmi-lesesaal.sln
      - name: Build
        run: msbuild cmi-lesesaal.sln /t:Rebuild /p:Configuration=Release 
      - name: Test
        run: packages\NUnit.ConsoleRunner.3.14.0\tools\nunit3-console.exe (ls -r Test\*\**\bin\release\*.Tests.dll | where-object { $_.FullName -notlike "*.Performance.Tests.dll" } | % { $_.FullName } | sort-object -Unique)
      - name: Check parameter documentation
        shell: pwsh
        run: |
          & .\CMI\Tools\UrbanCode\bin\Release\CMI.Tools.UrbanCode.exe d ${{github.workspace}} ${{runner.temp}}\Config-Dokumentation.html
